### ISSUE TITLE
Transport endpoint not connected 

### ISSUE THREAD

**Issue by eduardofcbg** [wiserain/docker-plexdrive#5]
After running ncdu on the mounted folder I got the message ‘Transport endpoint not connected’. It is no longer mounted, so I fix this by restarting the container.  
Is there any way to detect a failure when the location is not mounted and restart the service?

**Comment by wiserain** [comment]
maybe running a script periodically to check the mount and remount it if necessary? not sure for the moment. Btw it happened a lot? If plexdrive is used for its original purpose i.e. plex library, there should be no problem. Recommemed not running ncdu over the mount as it is highly restricted file system.

**Comment by eduardofcbg** [comment]
I think it is crashing because of low memory. Maybe this issue is not a relevant for this project. I'm yet to find out how what kind of crash is this, since the plexdrive process is still running...

**Comment by eduardofcbg** [comment]
It is crashing because of low memory. Right now the fusermount process is exiting with status 1. Docker already has restart policies so it only makes sense that it should be responsible for restarting the container

**Comment by eduardofcbg** [comment]
It is crashing because of low memory. Right now the fusermount process is exiting with status 1. Since you are using upstart here, maybe it makes sense for it to be responsible for restarting the service. I don't know how can this be accomplished.

**Comment by eduardofcbg** [comment]
https://github.com/plexdrive/plexdrive/issues/366

**Comment by wiserain** [comment]
I will add unmount process (fusermount -uz) when starting service to make sure proper mount.

**Comment by eduardofcbg** [comment]
Thanks. Here are the logs. I don’t know how you would go about  replicating this. 

```
[PLEXDRIVE] [2020-05-22 14:43] DEBUG  : fusermount: exit status 1
2020/05/22 14:43:03 mount helper error: fusermount: failed to access mountpoint /data: Transport endpoint is not connected
```

**Comment by wiserain** [comment]
Hope https://github.com/wiserain/docker-plexdrive/commit/34a929ff0cf90a47755066d04367ef64bd6ddb70 works!

**Comment by eduardofcbg** [comment]
Sorry, I had not time to test this yet.
Since you closed the issue I assume it is working correctly. Thanks for the improvement!
